import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import "../reset.css";
import Header from "@/components/header/header";
import LoginModal from "@/components/loginModal/loginModal";
import RegisterModal from "@/components/registerModal/registerModal";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <RegisterModal />
        <LoginModal />
        <Header />
        {children}
      </body>
    </html>
  );
}
